parameters:
#    osc_drink_order.example.class: Osc\Bundle\DrinkOrderBundle\Example

services:
#    osc_drink_order.example:
#        class: %osc_drink_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
